filter: 'winlog.event_data.TargetObject: ("HKLM\System\CurrentControlSet\Control\Lsa\Security
  Packages" OR "HKLM\System\CurrentControlSet\Control\Lsa\OSConfig\Security Packages")
  AND NOT (process.executable: "C:\Windows\system32\msiexec.exe" OR process.executable:
  "C:\Windows\syswow64\MsiExec.exe")'
pre_detector:
  case_condition: directly
  id: eeb30123-9fbd-4ee8-aaa0-2e545bbed6dc
  mitre:
  - attack.persistence
  - attack.t1101
  - attack.t1547.005
  severity: critical
  title: Security Support Provider (SSP) Added to LSA Configuration
sigma_fields: true
description: Detects the addition of a SSP to the registry. Upon a reboot or API call,
  SSP DLLs gain access to encrypted and plaintext passwords stored in Windows.