filter: 'winlog.event_data.TargetObject: ("*\services\TermService\Parameters\ServiceDll*"
  OR "*\Control\Terminal Server\fSingleSessionPerUser*" OR "*\Control\Terminal Server\fDenyTSConnections*")'
pre_detector:
  case_condition: directly
  id: 171b67e1-74b4-460e-8d55-b331f3e32d67
  mitre:
  - attack.defense_evasion
  - attack.t1112
  severity: high
  title: RDP Sensitive Settings Changed
sigma_fields: true
description: Detects changes to RDP terminal service sensitive settings