filter: 'winlog.event_data.TargetObject: ("*\Security\Trusted Documents\TrustRecords"
  OR "*\Security\AccessVBOM" OR "*\Security\VBAWarnings") AND winlog.event_data.EventType:
  ("SetValue" OR "DeleteValue" OR "CreateValue")'
pre_detector:
  case_condition: directly
  id: a166f74e-bf44-409d-b9ba-ea4b2dd8b3cd
  mitre:
  - attack.defense_evasion
  - attack.t1112
  severity: high
  title: Office Security Settings Changed
sigma_fields: true
description: Detects registry changes to Office macro settings