filter: '"ip http server" OR "ip https server" OR "kron policy-list" OR "kron occurrence"
  OR "policy-list" OR "access-list" OR "ip access-group" OR "archive maximum"'
pre_detector:
  case_condition: directly
  id: 671ffc77-50a7-464f-9e3d-9ea2b493b26b
  mitre:
  - attack.persistence
  - attack.impact
  - attack.t1490
  - attack.t1505
  - attack.t1493
  - attack.t1565.002
  - attack.t1168
  - attack.t1053
  severity: medium
  title: Cisco Modify Configuration
sigma_fields: true
description: Modifications to a config that will serve an adversary's impacts or persistence