filter: 'winlog.channel: "DNS Server" AND winlog.event_id: (150 OR 770)'
pre_detector:
  case_condition: directly
  id: cbe51394-cd93-4473-b555-edf0144952d9
  mitre:
  - attack.defense_evasion
  - attack.t1073
  - attack.t1574.002
  severity: critical
  title: DNS Server Error Failed Loading the ServerLevelPluginDLL
sigma_fields: true
description: This rule detects a DNS server error in which a specified plugin DLL
  (in registry) could not be loaded