filter: 'eventSource: "config.amazonaws.com" AND eventName: ("DeleteDeliveryChannel"
  OR "StopConfigurationRecorder")'
pre_detector:
  case_condition: directly
  id: 07330162-dba1-4746-8121-a9647d49d297
  mitre:
  - attack.defense_evasion
  - attack.t1562.001
  - attack.t1089
  severity: high
  title: AWS Config Disabling Channel/Recorder
sigma_fields: true
description: Detects AWS Config Service disabling